default:
  db:
    connection: "mongodb://root:root@ds055680.mongolab.com:55680/hi-track-location"

  parse_app_id: "TMG49CgTdo2aVoCXf6YWTnA9zwiQa68aPDblnOJv"
  parse_js_key: "7YgFfWumq8Tb6cHgAOmgDn1D3f5MxahAIJpK4Nwj"