default:
  db:
    connection: "mongodb://root:root@ds055680.mongolab.com:55680/hi-track-location"

  parse_app_id: "71OeWikSy4nxlGuefO2O6AFhuENP2Nqz1fjB88x3"
  parse_js_key: "LPYp2J4erP3V8A9KpmXhfbxAmcHjVfoxU9CLOfqU"